MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true

    after_initialize :ensure_session_token

    attr_reader :password

    validates :password, length: {minimum: 6}, allow_nil: true

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64(16)
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64(16)
    end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_user
        redirect_to new_user_url unless logged_in?
    end

    def login!(user)
        session[:session_token] = user.session_token
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end
    
    def show
        @band = Band.find(params[:id])
        render :show
    end

    def new
        @band = Band.new
        render :new
    end

    def create
        @band = Band.new(bands_params)
        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find_by(bands_params)
        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url 
    end

    def bands_params
        params.require(:band).permit(:name)
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.new[:errors] = ['Invalid Credentials']
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find_by_credentials(:email, :password)
        render :show
    end

    def create
        @user = User.new(users_params)

        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_url
        end
    end

    def users_params
        params.require(:user).permit(:email, :password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/bands/edit.html.erb
<h2>Edit <%= @band.name %></h2>

<form action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <label>Name
        <input type="text" name="band[name]" value="<%=@band.name%>">
    </label>

    <br>

    <input type="submit" value="Submit">
</form>

MusicApp/app/views/bands/index.html.erb
<h2>All the Bands!</h2>

<form action="<%= bands_url %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <ul>
        <% @bands.each do |band| %>
            <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
        <% end %>
    </ul>

    <a href="<%= new_band_url %>">New Band</a>

</form>

MusicApp/app/views/bands/new.html.erb
<h2>Create a New Band</h2>

<form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Name
        <input type="text" name="band[name]" value="<%=@band.name%>">
    </label>

    <br>

    <input type="submit" value="Submit">
</form>

MusicApp/app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

<a href="<%= edit_band_url(@band) %>">Edit Band</a>

<form action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete Band">
</form>

<a href="<%= bands_url %>">All Bands</a>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Turret+Road:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Inline&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400&display=swap" rel="stylesheet">
  </head>

  <body>
    <h1>Music App</h1>
    <% if logged_in? %>
      <p>Logged in as: <%= current_user.email %></p>
      <form action="<%= session_url %>" method="POST" class='log_out'>
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="DELETE">
          <input type="submit" value="Sign Out">
      </form>
    <% else %>
    <% end %>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
        <br>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<h2>New User</h2>

<form action="<%= users_url %>" method="POST" class="form">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <a href="<%= new_session_url %>">Go to Sign-in!</a>

    <br>

    <p>
        <label>Email
            <input type="text" name="user[email]" value="<%=@user.email%>">
        </label>
    </p>
  
    <br>

    <p>
        <label>Password
            <input type="password" name="user[password]" value="<%=@user.password%>">
        </label>
    </p>
    <br>

    <input type="submit" value="Submit">
</form>